# https://docs.docker.com/compose/environment-variables/

# version: '3.4'

services:
  gatewayServer:
    image: ${DOCKER_REGISTRY}gatewayServer
    build:
      context: authServer/
      dockerfile: gatewayServer/Dockerfile

  authServer:
    image: ${DOCKER_REGISTRY}authServer
    build:
      context: authServer/
      dockerfile: authServer/Dockerfile

  streamingServer:
    image: ${DOCKER_REGISTRY}streamingServer
    build:
      context: streamingServer/
      dockerfile: streamingServer/Dockerfile

  chatServer:
    image: ${DOCKER_REGISTRY}chatServer
    build:
      context: chatServer/
      dockerfile: chatServer/Dockerfile

  commentServer:
    image: ${DOCKER_REGISTRY}commentServer
    build:
      context: commentServer/
      dockerfile: commentServer/Dockerfile

  # # TO DO: add password to github or somewhere else instead of directly to the file
  # # Create a script that would create the necessary databases and run it on entrypoint
  # # Create a script to remove database data upon exiting the container
  # # https://stackoverflow.com/questions/41451159/how-to-execute-a-script-when-i-terminate-a-docker-container
  postgresServer:
    image: sqlserver # Sets the name of the image that will be built from Dockerfile
    container_name: ${POSTGRES_HOSTNAME}
    build:
      context: sqlServer/
      dockerfile: sqlServer/Dockerfile
      args:
        - POSTGRES_VERSION=${POSTGRES_VERSION}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_PORT=${POSTGRES_PORT}
        - POSTGRES_MAJOR_VERSION=${POSTGRES_MAJOR_VERSION}
        - POSTGRES_FULL_VERSION=${POSTGRES_FULL_VERSION}
    ports:
      - "${POSTGRES_PORT}:5432"

  adminer:
    image: adminer