# version: '3.4'
services:
  gatewayServer:
    image: ${DOCKER_REGISTRY-}gatewayServer
    build:
      context: .
      dockerfile: gatewayServer/Dockerfile

  authServer:
    image: ${DOCKER_REGISTRY-}authServer
    build:
      context: .
      dockerfile: authServer/Dockerfile


  streamingServer:
    image: ${DOCKER_REGISTRY-}streamingServer
    build:
      context: .
      dockerfile: streamingServer/Dockerfile

  chatServer:
    image: ${DOCKER_REGISTRY-}chatServer
    build:
      context: .
      dockerfile: chatServer/Dockerfile

  commentServer:
    image: ${DOCKER_REGISTRY-}commentServer
    build:
      context: .
      dockerfile: commentServer/Dockerfile

  sqlServer:
    image: postgres:15.0

  adminer:
    image: adminer