# https://www.composerize.com/
version: '3.3'
services:
    envoy-dev:
        container_name: envoy-container
        volumes:
            - './envoy.yaml:/etc/envoy/envoy.yaml' # overwrites default container's envoy.yaml file
        ports:
            - '8080:8080'
            # sita uzkomentavus vel grazina senaji teisinga "OK" koda OPTION'ui.
            # CIuju gaunasi, kad tiesiog nebeproxy'ina normaliai tada serveris ir tiek
            - '9090:9090'
            - '8999:8999'
        image: 'envoyproxy/envoy-dev:2ee5600abd1c64da0c0d0c8b12a9f6f5a3bf98e2'