services:
  gatewayServer:
    container_name: gatewayserver
    environment:
      # - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:80"
      - "8081:443" # SSL Port
      - "9090:9090"
      - "9091:9091" # SSL Port

  authServer:
    container_name: authserver
    environment:
      # - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "9092:9092"
      - "9093:9093"

  streamingServer:
    container_name: streamingserver
    environment:
      # - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "9094:9094"
      - "9095:9095"

  chatServer:
    container_name: chatserver
    environment:
      # - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "9096:9096"
      - "9097:9097"

  commentServer:
    container_name: commentserver
    environment:
      # - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "9098:9098"
      - "9099:9099"

  # TO DO: add password to github or somewhere else instead of directly to the file
  postgreServer:
    container_name: postgreserver
    image: postgres:14.4
    environment:
      - "POSTGRES_USER=root"
      - "POSTGRES_PASSWORD=example"
    volumes:
      - "./data:/var/lib/postgresql/data"
      # - ".\data\:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  adminer:
    container_name: adminer
    restart: always
    ports:
      - 8082:8080